diary

diff --git a/bash_notes b/bash_notes
--- a/bash_notes
+++ b/bash_notes
@@ -5,7 +5,9 @@ find <base_dir for search> -name <file or calalog name> -type d - ищем ка�
 
 find . -type f -path */objects/* -exec echo {} \; - выводит все файлы из текущего каталога (рекурсивно), путях которых есть участок /objects/
 
-find / -path */doc/* -name README > result_and_errors.txt 2>&1 - потоки stdout и stderr перенаправляются в указанный файл (вроде бы, на первый взгляд, должно быть что-то вроде 2>&1 > result_and_errors.txt - но это не так, верна первая конструкция: сначала поток вывода связывается с файлом, а потом поток ошибок перенаправляется в это файл)
+find / -path */doc/* -name README > result_and_errors.txt 2>&r" < "abc") || -z "$var" ]] && echo "Строка не пустая и меньше \
+чем abc или строка пустая"1 - потоки stdout и stderr перенаправляются в указанный файл (вроде бы, на первый взгляд, должно быть что-то вроде 2>&r" < "abc") || -z "$var" ]] && echo "Строка не пустая и меньше \
+чем abc или строка пустая"1 > result_and_errors.txt - но это не так, верна первая конструкция: сначала поток вывода связывается с файлом, а потом поток ошибок перенаправляется в это файл)
 
 find / -path */doc/* -name README > result.txt 2> errors.txt - для направления потока вывода и потока ошибок в разные файлы операторы перенаправления указываются друг за другом
 
@@ -209,4 +211,164 @@ echo "${contacts["$1"]}"
 
 unset contacts - удаление всего массива
 unset 'contacts[Bob]' - удаление элемента массива
+
+Условные операторы (ветвление)
+------------------
+if УСЛОВИЕ
+then
+  ДЕЙСТВИЕ
+fi
+
+if УСЛОВИЕ; then ДЕЙСТВИЕ; fi
+
+пример побайтового сравнения двух файлов с помощью утилиты cmp (в случае успеха код возврата будет 0):
+if cmp file1.txt file2.txt &> /dev/null
+then
+  echo "Файлы file1.txt и file2.txt идентичны"
+fi
+
+if УСЛОВИЕ
+then
+  ДЕЙСТВИЕ 1
+else
+  ДЕЙСТВИЕ 2
+fi
+
+if УСЛОВИЕ; then ДЕЙСТВИЕ 1; else ДЕЙСТВИЕ 2; fi
+
+if cmp file1.txt file2.txt &> /dev/null
+then
+  echo "Файлы file1.txt и file2.txt идентичны"
+else
+  echo "Файлы file1.txt и file2.txt различаются"
+fi
+
+if УСЛОВИЕ 1
+then
+  ДЕЙСТВИЕ 1
+elif УСЛОВИЕ 2
+then
+  ДЕЙСТВИЕ 2
+else
+  ДЕЙСТВИЕ 3
+fi
+
+if УСЛОВИЕ 1; then ДЕЙСТВИЕ 1; elif УСЛОВИЕ 2; then ДЕЙСТВИЕ 2; else ДЕЙСТВИЕ 3; fi
+
+Применение техники "раннего возврата" (идея в том, чтобы в случае ошибки завершить программу как можно раньше: если неудача, происходит выход из программы с кодом 1):
+if ! bsdtar -cjf "$1".tar.bz2 "$@"
+then
+  echo "bsdtar - FAILS" > results.txt
+  exit 1
+fi
+echo "bsdtar - OK" > results.txt
+
+if ! ДЕЙСТВИЕ_1 # т.е. в результате действия получаем результат, противоположный ожидаемому
+then
+# обработка ошибки
+fi
+
+if ! ДЕЙСТВИЕ_2
+then
+# обработка ошибки
+fi
+
+if ! ДЕЙСТВИЕ_3
+then
+# обработка ошибки
+fi
+
+if ! ДЕЙСТВИЕ_4
+then
+# обработка ошибки
+fi
+
+ДЕЙСТВИЕ_5
+
+Оператор [[ - двойные квадратные скобки являются зарезервированным словом. Это значит, что интерпретатор обрабатывает его самостоятельно
+
+сравниваем две строки:
+if [[ "abc" = "abc" ]]
+then
+echo "Строки равны"
+fi
+
+сравниваем значение переменной со строкой:
+if [[ "$var" = "abc" ]]
+then
+echo "Переменная равна строке \"abc\""
+fi
+
+сравниваем значения двух переменных:
+if [[ "$var" = "$filename" ]]
+then
+echo "Переменные равны"
+fi
+
+Операции сравнения строк в операторе
+------------------
+[[ "aaa" < "bbb" ]] && echo "Строка aaa меньше строки bbb"
+> - строка слева больше строки справа в порядке лексикографической сортировки
+= или == - строки равны
+!= - строки не равны
+-z - строка пустая
+-n - строка не пустая
+-v - переменная объявлена с любым значением
+= или == - поиск в строке слева подстроки по шаблону справа: [[ "$filename"=READ*]] && echo "Имя файла начинается с READ"
+!= - проверка, что шаблон справа не встречается в строке слева: [[ "$filename"!=READ* ]] && echo "Имя файла не начинается с READ*"
+=~ - поиск в строке слева подстроки по регулярному выражению справа: [[ "$filename"=~^READ* ]] && echo "Имя файла начинается с READ"
+
+Логические операции в операторе [[
+-------------------
+&& - Логическое И: [[ -n “$var” && “$var” < “abc” ]] && echo “Строка не пустая и меньше чем abc”
+|| - Логическое ИЛИ: [[ “abc” < “$var” || -z “$var” ]] && echo “Строка больше чем abс или пустая”
+! - Логическое НЕ: [[ ! “abc” < “$var” ]] && echo “Строка не больше чем abc”
+
+выражения в операторе [[ можно группировать с помощью круглых скобок. Например, так:
+[[ (-n "$var" && "$var" < "abc") || -z "$var" ]] && echo "Строка не пустая и меньше \
+чем abc или строка пустая"
+
+Операции проверки файлов в операторе [[
+-----------------
+-e	Файл существует: 	[[ -e “$filename” ]] && echo “Файл $filename существует”
+
+-f	Указанный объект является обычным файлом (не каталогом и не файлом устройства):
+[[ -f “~/README.txt” ]] && echo “README.txt - это обычный файл”
+
+-d	Указанный объект является каталогом:	[[ -f “/usr/bin” ]] && echo “/usr/bin - это каталог”
+
+-s	Файл не пустой:		[[ -s “$filename” ]] && echo “Файл $filename не пустой”
+
+-r	Файл существует и доступен для чтения пользователю, запустившему скрипт:
+[[ -r “$filename” ]] && echo “Файл $filename существует и доступен для чтения”
+
+-w	Файл существует и доступен для записи пользователю, запустившему скрипт:
+[[ -w “$filename” ]] && echo “Файл $filename существует и доступен для записи”
+
+-x	Файл существует и доступен для исполнения пользователю, запустившему скрипт:
+[[ -x “$filename” ]] && echo “Файл $filename существует и доступен для исполнения”
+
+-N	Файл существует и был модифицирован с момента последнего чтения: 
+[[ -N “$filename” ]] && echo “Файл $filename существует и был модифицирован”
+
+-nt	Файл слева от оператора новее, чем файл справа. Либо файл слева существует, а справа - нет:
+[[ “$file1” -nt “$file2” ]] && echo “Файл $file1 новее чем $file2”
+
+-ot	Файл слева от оператора старее, чем файл справа. Либо файл справа существует, а слева — нет:
+[[ “$file1” -ot “$file2” ]] && echo “Файл $file1 старее чем $file2”
+
+-ef	Слева и справа от оператора указан путь до одного и того же существующего файла. Если ваша система поддерживает
+жёсткие ссылки, то ссылки слева и справа от оператора указывают на один и тот же файл:
+[[ “$file1” -ef “$file2” ]] && echo “Файлы $file1 и $file2 совпадают”
+
+Операции сравнения целых чисел в операторе [[
+------------------
+-eq	Число слева равно числу справа:		[[ “$var” -eq 5 ]] && echo “Переменная равна 5”
+-ne	Не равно:	[[ “$var” -ne 5 ]] && echo “Переменная не равна 5”
+-gt	Больше (>):	[[ “$var” -gt 5 ]] && echo “Переменная больше 5”
+-ge	Больше или равно:	[[ “$var” -ge 5 ]] && echo “Переменная больше или равна 5”
+-lt	Меньше (<):	[[ “$var” -lt 5 ]] && echo “Переменная меньше 5”
+-le	Меньше или равно:	[[ “$var” -le 5 ]] && echo “Переменная меньше или равна 5”
+
+
 
