updated bash_notes

diff --git a/bash_notes b/bash_notes
--- a/bash_notes
+++ b/bash_notes
@@ -370,5 +370,537 @@ fi
 -lt	Меньше (<):	[[ “$var” -lt 5 ]] && echo “Переменная меньше 5”
 -le	Меньше или равно:	[[ “$var” -le 5 ]] && echo “Переменная меньше или равна 5”
 
+Оператор case применяется в общем случае так:
+case СТРОКА in
+  ШАБЛОН_1)
+    ДЕЙСТВИЕ_1
+    ;;
+
+  ШАБЛОН_2)
+    ДЕЙСТВИЕ_2
+    ;;
+
+  ШАБЛОН_3)
+    ДЕЙСТВИЕ_3
+    ;;
+
+  ШАБЛОН_4)
+    ДЕЙСТВИЕ_4
+    ;;
+esac
+
+Варианты ветвления на основе if, case и ассоциативного массива
+------------------
+У скрипта есть три режима работы: архивация со сжатием, архивация без сжатия и разархи-
+вация. Нужное действие выбирается с помощью опции скрипта. Один из вариантов опций:
+-a - Архивация без сжатия
+-c - Архивация со сжатием
+-x - Разархивация
+
+Скрипт архивации документа на основе if:
+#!/bin/bash
+operation="$1"
+if [[ "$operation" == "-a" ]]
+then
+  bsdtar -c -f documents.tar ~/Documents
+elif [[ "$operation" == "-c" ]]
+then
+  bsdtar -c -j -f documents.tar.bz2 ~/Documents
+elif [[ "$operation" == "-x" ]]
+then
+  bsdtar -x -f documents.tar*
+else
+  echo "Указана недопустимая опция"
+  exit 1
+fi
+
+Скрипт архивации документа на основе case:
+#!/bin/bash
+operation="$1"
+case "$operation" in
+  "-a")
+    bsdtar -c -f documents.tar ~/Documents
+    ;;
+  "-c")
+    bsdtar -c -j -f documents.tar.bz2 ~/Documents
+    ;;
+  "-x")
+    bsdtar -x -f documents.tar*
+    ;;
+  *)
+    echo "Указана недопустимая опция"
+    exit 1
+    ;;
+esac
+
+Скрипт-обертка над утилитами bsdtar и tar:
+#!/bin/bash
+utility="$1"
+
+case "$utility" in
+  "-b"|"--bsdtar")
+    bsdtar "${@:2}"
+    ;;
+
+  "-t"|"--tar")
+    tar "${@:2}"
+    ;;
+
+  *)
+    echo "Указана недопустимая опция"
+    exit 1
+    ;;
+esac
+
+Скрипт архивации на основе ассоциативного массива:
+#!/bin/bash
+option="$1"
+
+declare -A utils=(
+  ["-b"]="bsdtar"
+  ["--bsdtar"]="bsdtar"
+  ["-t"]="tar"
+  ["--tar"]="tar")
+
+if [[ -z "$option" || ! -v utils["$option"] ]]
+then
+  echo "Указана недопустимая опция"
+  exit 1
+fi
+
+${utils["$option"]} "${@:2}"
 
 
+Bash выполняет целочисленную арифметику.
+Результат сложения двух целых чисел сохраняем в переменной, которую объявляем с целочисленным атрибутом:
+declare -i var=12+7 # результатом будет число 19, а не "12+7"
+
+Математический контекст можно объявить явно с помощью команды let:
+let text=5*7 # результатом будет запись в переменную text числа 35
+
+Примеры объявления, передачи значений и расчета с помощью команды let:
+let a=1+1 b=5+1 # без кавычек и пробелов (иначе возможен word spliting)
+let "a = 1 + 1" "b = 5 + 1" # двойные кавычки дают возможность поставить пробел
+let 'a = 1 + 1' 'b = 5 + 1' # то же касается и одинарных кавычек
+
+У команды let есть синоним - оператор ((. Внутри него word spliting не выполняется.
+Оператор имеет две формы. 
+Первая называется арифметической оценкой и эквивалентна let:
+((var1 = 5 + 9))
+Эта форма оператора (( возвращает код ноль при успешном выполнении и единицу в случае ошибки.
+Вторая форма называется арифметической подстановкой:
+var=$((5+9))
+В этом случае оператор вернет результат арифметической операции (здесь - 14)
+
+В операторе (( имена переменных можно указывать без знака доллар $. Bash всё равно
+правильно подставит их значения. Например, следующие два выражения для вычисления
+result эквивалентны:
+a=5 b=10
+result=$(($a + $b))
+result=$((a + b))
+
+В обоих случаях переменная result станет равна 15.
+Не используйте знак доллара в операторе ((. Это сделает ваш код чище и понятнее.
+
+
+Операции с арифметических выражениях
+------------------------------------
+
+Вычисления
+*	Умножение				echo "$((2 * 9)) = 18"
+/	Деление					echo "$((25 / 5)) = 5"
+%	Остаток от деления			echo "$((8 % 3)) = 2"
++	Сложение				echo "$((7 + 3)) = 10"
+-	Вычитание				echo "$((8 - 5)) = 3"
+**	Возведение в степень			echo "$((4**3)) = 64"
+
+Битовые операции
+~	Побитовое НЕ (NOT)			echo "$((∼5)) = -6"
+<<	Битовый сдвиг влево			echo "$((5 << 1)) = 10"
+>>	Битовый сдвиг вправо			echo "$((5 >> 1)) = 2"
+&	Побитовое И (AND)			echo "$((5 & 4)) = 4"
+|	Побитовое ИЛИ (OR)			echo "$((5 | 2)) = 7"
+^	Побитовое исключающее	ИЛИ(XOR)	echo "$((5 ^ 4)) = 1"
+
+Присваивания
+=	Обычное присваивание			echo "$((num = 5)) = 5"
+*=	Умножение и присваивание 
+	результата				echo "$((num *= 2)) = 10"
+/=	Деление и присваивание
+	результата				echo "$((num /= 2)) = 5"
+%=	Остаток от деления и
+	присваивание результата			echo "$((num %= 2)) = 1"
++=	Сложение и присваивание
+	результата				echo "$((num += 7)) = 8"
+-=	Вычитание и присваивание
+	результата				echo "$((num -= 3)) = 5"
+<<=	Битовый сдвиг влево и
+	присваивание результата			echo "$((num <<= 1)) = 10
+>>=	Битовый сдвиг вправо и
+	присваивание результата			echo "$((num >>= 2)) = 2"
+&=	Побитовое И (AND), затем
+	присваивание результата			echo "$((num &= 3)) = 2"
+^=	Побитовое исключающее ИЛИ
+	(XOR), затем присваивание
+	результата				echo "$((num^=7)) = 5"
+|=	Побитовое ИЛИ (OR), затем
+	присваивание результата			echo "$((num |= 7)) = 7"
+
+Сравнения
+<	Меньше			((num < 5)) && echo "переменная num меньше 5"
+>	Больше			((num > 5)) && echo	"переменная num больше 3"
+<=	Меньше или равно	((num <= 20)) && echo "переменная num меньше или равна 20"
+>=	Больше или равно	((num >= 15)) && echo "переменная num больше или равна 15"
+==	Равно			((num == 3)) && echo "переменная num равна 3"
+!=	Не равно		((num != 3)) && echo "переменная num не равна 3"
+
+Логические операции
+!	Логическое НЕ (NOT)	(( ! num )) && echo "переменная num имеет значение ЛОЖЬ"
+&&	Логическое И (AND)	(( 3 < num && num < 5 )) && echo "переменная num больше 3, но меньше 5"
+||	Логическое ИЛИ (OR)	(( num < 3 || 5 < num )) && echo "переменная num меньше 3 или больше 5"
+
+Другие операции
+num++	Постфикс-инкремент	echo "$((num++))"
+num--	Постфикс-декремент	echo "$((num--))"
+++num	Префикс-инкремент	echo "$((++num))"
+--num	Префикс-декремент	echo "$((--num))"
++num	Унарный плюс или умножение числа на  1	a=$((+num))"
+-num	Унарный минус или умножение числа на -1	a=$((-num))"
+УСЛОВИЕ ? ДЕЙСТВИЕ1 : ДЕЙСТВИЕ2	Тернарная условная операция a=$(( b < c ? b : c ))
+ДЕЙСТВИЕ1, ДЕЙСТВИЕ2 Список выражений ((a = 4 + 5, b = 16 - 7))
+( ДЕЙСТВИЕ1 ) Группирование выражений(подвыражение)	a=$(( (4 + 5) * 2 ))
+
+Порядок выполнения арифметических операций
+------------------------------------------
+1	( ДЕЙСТВИЕ1 )	Группирование выражений
+2	num++, num--	Постфиксный инкремент и декремент
+3	++num, --num	Префиксный инкремент и декремент
+4	+num, -num		Унарный плюс и минус
+5	~, ! Побитовое и логическое отрицание
+6	**	Возведение в степень
+7	*, /, %	Умножение, деление, нахождение остатка
+8	+, -	Сложение и вычитание
+9	<<, >>	Битовые сдвиги
+10	<, <=, >, >=	Сравнения
+11	==, !=	Равенство и неравенство
+12	&	Побитовое И
+13	^	Побитовое исключающее ИЛИ
+14	|	Побитовое ИЛИ
+15	&&	Логическое И
+16	||	Логическое ИЛИ
+17	УСЛОВИЕ ? ДЕЙСТВИЕ1 : ДЕЙСТВИЕ2	Тернарная условная операция
+18	=, *=, /=, %=, +=, -=, <<=, >>=, &=, ^=, |=		Присваивания
+19	ДЕЙСТВИЕ1, ДЕЙСТВИЕ2	Список выражений
+
+Порядок выполнения можно изменить с помощью круглых скобок “( )”. Их содержимое называется подвыражением (subexpression). Bash вычисляет значения подвыражений в первую очередь. Если подвыражений несколько, они вычисляются по порядку.
+
+Префиксы для указания системы счисления константы
+-------------------------------------------------
+0	Восьмеричная		echo "$((071)) = 57"
+0x	Шестнадцатеричная	echo "$((0xFF)) = 255"
+0X	Шестнадцатеричная	echo "$((0XFF)) = 255"
+<основание>#	Система с указанным основанием от 2 до 64	echo "$((16#FF)) = 255"
+															echo "$((2#101)) = 5"
+
+При выводе на экран или в файл Bash всегда переводит значения чисел в десятичную систему. Встроенная команда printf меняет формат вывода чисел. Её можно вызвать, например, так: 
+printf "%x\n" 250
+Эта команда выведет на экран число 250 в шестнадцатеричной системе. Аналогично можно вывести и значение переменной:
+printf "%x\n" $var
+
+$((30 / 7 )) - целочисленное деление (вернет 4)
+$((30 / 7)) - остаток от деления (вернет 2)
+
+if ((1 < var && var < 5))
+then
+  echo "Значение var меньше 5, но больше 1"
+fi
+
+if ((var < 1 || 5 < var))
+then
+  echo "Значение var меньше 1 или больше 5"
+fi
+
+Логическое НЕ редко применяется к самим числам. Чаще его используют для отрицания выражения. Если применить НЕ к числу, вывод результата соответствует POSIX-стандарту. Другими словами ноль означает истинна, а не ноль — ложь. Например:
+if ((! var))
+then
+  echo "Значение var равно истина или ноль"
+fi
+
+Инкременты и декременты:
+((++var))  ((--var)) ((var++)) ((var--))
+Всегда используйте префиксную форму инкремента и декремента вместо постфиксной. Во-первых, она быстрее выполняется процессором. Потому что не надо сохранять текущее значение переменной. Во-вторых, с постфиксной формой легче допустить ошибку из-за неочевидного порядка присваивания.
+Bash поддерживает операции присваивания с арифметическим действием, например: 
+((var+=1)) ((var-=1)) и т.д.
+
+Тернарная условная операция:
+Для примера рассмотрим такой оператор if:
+if ((var < 10))
+then
+  ((result = 0))
+else
+  ((result = var))
+fi
+
+Здесь переменной result присваивается ноль, если var меньше 10. В противном случае
+result присваивается значение var.
+Такое же поведение даст тернарный оператор. Он выглядит так:
+((result = var < 10 ? 0 : var))
+Одна строка заменила шесть строк конструкции if.
+
+Тернарный оператор состоит из условного выражения и двух действий. В общем случае он
+выглядит так:
+(( УСЛОВИЕ ? ДЕЙСТВИЕ 1 : ДЕЙСТВИЕ 2 ))
+
+
+Операторы цикла
+---------------
+В Bash есть два оператора цикла: while и for. Сначала познакомимся с оператором while. Он проще чем for. Синтаксис while напоминает условный оператор if. В общем виде он выглядит так:
+while УСЛОВИЕ
+do
+  ДЕЙСТВИЕ
+done
+
+Оператор можно записать в одну строку:
+while УСЛОВИЕ; do ДЕЙСТВИЕ; done
+
+В конструкции while УСЛОВИЕМ и ДЕЙСТВИЕМ может быть одна команда или блок команд. Точно так же как в операторе if. ДЕЙСТВИЕ называется телом цикла (loop body). Выполнение while начинается с проверки УСЛОВИЯ. Если команда УСЛОВИЯ вернула нулевой код, оно считается истинным. В этом случае выполняется ДЕЙСТВИЕ. Дальше опять проверяется УСЛОВИЕ. Если оно по-прежнему истинно, снова выполняется ДЕЙСТВИЕ. Цикл прервётся тогда, когда УСЛОВИЕ станет ложным. Используйте цикл while, когда количество итераций заранее неизвестно. Например, при активном ожидании какого-то события.
+
+Кроме while в Bash есть оператор цикла for. Используйте его, когда количество итераций известно заранее. У оператора for есть две формы. Первая нужна для последовательной обработки слов в строке. Во второй форме условием цикла выступает арифметическое выражение.
+
+Начнём с первой формы for. В общем виде она выглядит так:
+for ПЕРЕМЕННАЯ in СТРОКА
+do
+  ДЕЙСТВИЕ
+done
+
+В однострочном виде эта же конструкция записывается так:
+for ПЕРЕМЕННАЯ in СТРОКА; do ДЕЙСТВИЕ; done
+
+ДЕЙСТВИЕМ в конструкции for может быть одна команда или блок команд. Точно так же как в операторе while.
+
+Скрипт для обработки слов в строке:
+#!/bin/bash
+for word in $1
+do
+  echo "$word"
+done
+
+Передаваемую в скрипт строку надо заключить в кавычки. Тогда она целиком попадёт в позиционный параметр $1. Например:
+./for-string.sh "this is a string"
+
+Проблему кавычек при передаче строки в скрипт можно решить. Замените в условии цикла
+позиционный параметр $1 на $@. Получится такая конструкция for:
+for word in $@
+do
+  echo "$word"
+done
+
+Теперь сработают оба варианта вызова скрипта:
+./for-string.sh this is a string
+./for-string.sh "this is a string"
+
+Цикл for позволяет пройти по элементам индексируемого массива. Это работает так же, как перебор слов в строке. 
+Скрипт для обработки всех элементов массива
+#!/bin/bash
+array=(Alice Bob Eve Mallory)
+for element in "${array[@]}"
+do
+  echo "$element"
+done
+Скрипт для обработки первых трех элементов массива
+#!/bin/bash
+array=(Alice Bob Eve Mallory)
+for element in "${array[@]:0:2}"
+do
+  echo "$element"
+done
+
+Другой вариант — перебирать в цикле не сами элементы, а их индексы. Запишем индексы нужных элементов через пробел. Затем пройдём по ним в цикле. Получится следующее:
+array=(Alice Bob Eve Mallory)
+for i in 0 1 2
+do
+  echo "${array[i]}"
+done
+
+array=(Alice Bob Eve Mallory)
+for i in {0..2}
+do
+  echo "${array[i]}"
+done
+
+Во второй форме оператора for условием цикла выступает арифметическое выражение.
+Скрипт для расчета факториала числа 5
+#!/bin/bash
+result=1
+for i in {1..5}
+do
+  ((result *= $i))
+done
+echo "Факториал числа 5 равен $result"
+
+Способы вызова утилиты seq:
+seq 5 (конечное число) вернет последовательность 1 2 3 4 5
+seq -2 2 (начало, конец) вернет последовательность -2 -1 0 1 2
+seq 1 2 5 (начало, конец, шаг) вернет последовательность 1 3 5 
+Например: for i in $(seq -3 3); do echo $i; done - вернет -3 -2 -1 0 1 2 3 
+
+Скрипт для расчета факториала
+#!/bin/bash
+result=1
+for i in $(seq $1)
+do
+  ((result *= $i))
+done
+echo "Факториал числа $1 равен $result"
+
+Это решение работает. Однако, его нельзя назвать эффективным. В условии цикла for вызывается внешняя утилита. 
+
+Для решения задачи нам пригодится вторая форма оператора for. В общем виде она выглядит так:
+for (( ВЫРАЖЕНИЕ_1; ВЫРАЖЕНИЕ_2; ВЫРАЖЕНИЕ_3 ))
+do
+  ДЕЙСТВИЕ
+done
+
+В однострочном виде эта конструкция записывается так:
+for (( ВЫРАЖЕНИЕ_1; ВЫРАЖЕНИЕ_2; ВЫРАЖЕНИЕ_3 )); do ДЕЙСТВИЕ; done
+
+Цикл for с арифметическим условием работает так:
+1. ВЫРАЖЕНИЕ_1 выполняется однократно перед первой итерацией цикла.
+2. Цикл выполняется до тех пор, пока ВЫРАЖЕНИЕ_2 остаётся истинным. Как только оно
+вернуло ложь в качестве результата, цикл завершается.
+3. В конце каждой итерации выполняется ВЫРАЖЕНИЕ_3.
+
+Скрипт для расчета факториала
+#!/bin/bash
+result=1
+for (( i = 1; i <= $1; ++i ))
+do
+  ((result *= i))
+done
+echo "Факториал числа $1 равен $result"
+
+Цикл завершается согласно своему условию. Кроме условия есть дополнительные средства для управления циклом. 
+
+Встроенная команда break немедленно прекращает выполнение цикла. Она полезна для обработки ошибок или выхода из бесконечного цикла.
+
+Скрипт для поиска элемента в массиве
+#!/bin/bash
+array=(Alice Bob Eve Mallory)
+is_found="0"
+for element in "${array[@]}"
+do
+  if [[ "$element" == "$1" ]]
+  then
+    is_found="1"
+  break
+  fi
+done
+if [[ "$is_found" -ne "0" ]]
+then
+  echo "Элемент со значением $1 есть в массиве"
+else
+  echo "Элемента со значением $1 нет в массиве"
+fi
+
+#!/bin/bash
+array=(Alice Bob Eve Mallory)
+for element in "${array[@]}"
+do
+  if [[ "$element" == "$1" ]]
+  then
+    echo "Элемент со значением $1 есть в массиве"
+    exit 0
+  fi
+done
+echo "Элемента со значением $1 нет в массиве"
+
+Встроенная команда continue прекращает исполнение текущей итерации цикла. При этом цикл не завершится. Он продолжит выполняться со следующей итерации.
+
+Скрипт для расчета суммы положительних чисел в массиве
+#!/bin/bash
+array=(1 25 -5 4 -9 3)
+sum=0
+for element in "${array[@]}"
+do
+  if (( 0 < element ))
+  then
+    ((sum += element))
+  fi
+done
+echo "Сумма положительных чисел равна $sum"
+
+Теперь используем команду continue:
+#!/bin/bash
+array=(1 25 -5 4 -9 3)
+sum=0
+for element in "${array[@]}"
+do
+  if (( element < 0))
+  then
+    continue
+  fi
+  ((sum += element))
+done
+echo "Сумма положительных чисел равна $sum"
+
+Функции
+-------
+Функции доступны в обоих режимах Bash: командный интерпретатор и исполнение скриптов. 
+
+Начнём с командного интерпретатора. В общем виде функция объявляется так:
+ИМЯ_ФУНКЦИИ()
+{
+ДЕЙСТВИЕ
+}
+В одну строку функцию можно объявить так:
+ИМЯ_ФУНКЦИИ() { ДЕЙСТВИЕ ; }
+Обратите внимание на обязательную точку с запятой перед закрывающей фигурной скобкой}.
+
+Тело функции ДЕЙСТВИЕ может быть одной командой или блоком команд.
+
+В скриптах функции объявляются точно так же, как в командном интерпретаторе. Допускаются оба варианта объявления: стандартный и однострочный. Для примера вернёмся к проблеме обработки ошибок в большой программе. Объявим следующую функцию для вывода сообщений об ошибках:
+print_error()
+{
+  >&2 echo "Произошла ошибка: $@"
+}
+Текст, объясняющий причину ошибки, передаётся в функцию через параметр. Допустим, наша программа читает файл на диске. Но файл оказался недоступен. Тогда сообщить о проблеме можно так:
+print_error "файл readme.txt не найден"
+
+Встречаются ситуация, когда одна функция должна вызвать другую. 
+
+Напишем функцию для конвертирования кода ошибки в сообщение. Для конвертирования применим конструкцию case. Каждый блок case соответствует определённому коду ошибки.
+Объявление функции выглядит так:
+code_to_error()
+{
+  case $1 in
+    1)
+      echo "Не найден файл"
+      ;;
+    2)
+      echo "Нет прав для чтения файла" 
+      ;;
+    esac
+}
+
+Теперь перепишем объявление функции print_error так:
+print_error()
+{
+  echo "$(code_to_error $1) $2" >> debug.log
+}
+
+Вызов функции print_error выглядит, например, так:
+print_error 1 "readme.txt"
+
+В результате вызова в лог-файл запишется строка:
+Не найден файл readme.txt
+
+Первым параметром в функцию передаётся код ошибки. Вторым параметром — имя файла, который привёл к проблеме.
+
+Чтобы вернуть результат функции, процедурные языки имеют встроенную команду. Обычно она называется return. В Bash эта команда тоже есть. Но её поведение отличается. Команда return в Bash не возвращает значение. Она передаёт код возврата, то есть целое число от 0 до 255.
+
+Полный алгоритм вызова и выполнения функции выглядит так:
+1. При выполнении команды встречается имя функции.
+2. Интерпретатор переходит в тело функции и исполняет его с первой команды.
+3. Если в теле функции встречается команда return, выполнение функции прекращается.
+Bash переходит в место её вызова. В специальный параметр $? записывается кодвозврата функции. Это параметр команды return.
+4. Если в теле функции нет return, Bash выполняет его до последней команды. После этого интерпретатор переходит в место вызова функции.
